language: minimal

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

install:
  - echo "Nothing needs to be installed"

script:
  - docker-compose -f deployment/docker/docker-compose-build.yaml build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f deployment/docker/docker-compose-build.yaml push
